import { useContext } from 'react'
import { FirstContext, SecondContext } from '../App'

const Level3 = () => {
  const { value: firstValue } = useContext(FirstContext)
  const { value: secondValue, setValue: setSecondValue } =
    useContext(SecondContext)

  const handleChange = () => {
    setSecondValue?.('New Level3 value, generated by Level3 component')
  }

  return (
    <div>
      <h2>Level3: {firstValue}</h2>
      <h2>
        Level3: <span style={{ color: '#ff0000' }}>{secondValue}</span>
      </h2>
      <button onClick={handleChange}>Change Level3 value</button>
    </div>
  )
}

export default Level3
