import { useContext } from 'react'
import { SecondContext } from '../App'

const Second = () => {
  const { value: secondValue, setValue: setSecondValue } =
    useContext(SecondContext)

  const handleChange = () => {
    setSecondValue?.('New SecondContext value, generated by Second component')
  }

  return (
    <div>
      <h2>
        Second: <span style={{ color: '#0000ff' }}>{secondValue}</span>
      </h2>
      <button onClick={handleChange}>Change SecondContext value</button>
    </div>
  )
}

export default Second
